spring:
  application:
    name: event-service
  config.import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: dev
  mvc:
    log-resolved-exception: true

server:
  forward-headers-strategy: framework
